% 无人机1
% 方向
drone_dir = [-sign(alpha) * cos(alpha), abs(sin(alpha))];
% 约束条件
% 第1个烟雾弹
constraints11 = @(alpha,t_deploy1,drone_speed,t_explode_delay1)  abs(missile1_vel(1)) * (t_deploy1+t_explode_delay1) - 2200 ...
    - sign(alpha) * drone_speed * cos(alpha) * (t_deploy1+t_explode_delay1);
constraints12 = @(alpha,t_deploy1,drone_speed,t_explode_delay1)  abs(missile2_vel(1)) * (t_deploy1+t_explode_delay1) - 2100 ...
    - sign(alpha) * drone_speed * cos(alpha) * (t_deploy1+t_explode_delay1);
constraints13 = @(alpha,t_deploy1,drone_speed,t_explode_delay1)  abs(missile3_vel(1)) * (t_deploy1+t_explode_delay1) - 2000 ...
    - sign(alpha) * drone_speed * cos(alpha) * (t_deploy1+t_explode_delay1);


% 第2个烟雾弹
constraints21 = @(alpha,t_deploy2,drone_speed,t_explode_delay2)  abs(missile1_vel(1)) * (t_deploy2+t_explode_delay2) - 2200 ...
    - sign(alpha) * drone_speed * cos(alpha) * (t_deploy2+t_explode_delay2);
constraints22 = @(alpha,t_deploy2,drone_speed,t_explode_delay2)  abs(missile2_vel(1)) * (t_deploy2+t_explode_delay2) - 2100 ...
    - sign(alpha) * drone_speed * cos(alpha) * (t_deploy2+t_explode_delay2);
constraints23 = @(alpha,t_deploy2,drone_speed,t_explode_delay2)  abs(missile3_vel(1)) * (t_deploy2+t_explode_delay2) - 2000 ...
    - sign(alpha) * drone_speed * cos(alpha) * (t_deploy2+t_explode_delay2);

% 第3个烟雾弹
constraints31 = @(alpha,t_deploy3,drone_speed,t_explode_delay3)  abs(missile1_vel(1)) * (t_deploy3+t_explode_delay3) - 2200 ...
    - sign(alpha) * drone_speed * cos(alpha) * (t_deploy3+t_explode_delay3);
constraints32 = @(alpha,t_deploy3,drone_speed,t_explode_delay3)  abs(missile2_vel(1)) * (t_deploy3+t_explode_delay3) - 2100 ...
    - sign(alpha) * drone_speed * cos(alpha) * (t_deploy3+t_explode_delay3);
constraints33 = @(alpha,t_deploy3,drone_speed,t_explode_delay3)  abs(missile3_vel(1)) * (t_deploy3+t_explode_delay3) - 2000 ...
    - sign(alpha) * drone_speed * cos(alpha) * (t_deploy3+t_explode_delay3);


% 无人机2和无人机4
% 方向
drone_dir = [-cos(alpha),-sin(alpha)];  % 范围[0,pi]
% 第1个烟雾弹
constraints11 = @(alpha,t_deploy1,drone_speed,t_explode_delay1)  abs(missile1_vel(1)) * (t_deploy1+t_explode_delay1) - missile1_pos0(1) + drone_pos0(1) ...
    +drone_speed * cos(alpha) * (t_deploy1+t_explode_delay1);
constraints12 = @(alpha,t_deploy1,drone_speed,t_explode_delay1)  abs(missile2_vel(1)) * (t_deploy1+t_explode_delay1) - missile2_pos0(1) + drone_pos0(1) ...
    + drone_speed * cos(alpha) * (t_deploy1+t_explode_delay1);
constraints13 = @(alpha,t_deploy1,drone_speed,t_explode_delay1)  abs(missile3_vel(1)) * (t_deploy1+t_explode_delay1) - missile2_pos0(1) + drone_pos0(1) ...
    + drone_speed * cos(alpha) * (t_deploy1+t_explode_delay1);


% 第2个烟雾弹
constraints21 = @(alpha,t_deploy2,drone_speed,t_explode_delay2)  abs(missile1_vel(1)) * (t_deploy2+t_explode_delay2) - missile1_pos0(1) + drone_pos0(1)...
    + drone_speed * cos(alpha) * (t_deploy2+t_explode_delay2);
constraints22 = @(alpha,t_deploy2,drone_speed,t_explode_delay2)  abs(missile2_vel(1)) * (t_deploy2+t_explode_delay2) - missile2_pos0(1) + drone_pos0(1) ...
    + drone_speed * cos(alpha) * (t_deploy2+t_explode_delay2);
constraints23 = @(alpha,t_deploy2,drone_speed,t_explode_delay2)  abs(missile3_vel(1)) * (t_deploy2+t_explode_delay2) - missile3_pos0(1) + drone_pos0(1) ...
    + drone_speed * cos(alpha) * (t_deploy2+t_explode_delay2);

% 第3个烟雾弹
constraints31 = @(alpha,t_deploy3,drone_speed,t_explode_delay3)  abs(missile1_vel(1)) * (t_deploy3+t_explode_delay3) - missile1_pos0(1) + drone_pos0(1) ...
    + drone_speed * cos(alpha) * (t_deploy3+t_explode_delay3);
constraints32 = @(alpha,t_deploy3,drone_speed,t_explode_delay3)  abs(missile2_vel(1)) * (t_deploy3+t_explode_delay3) - missile2_pos0(1) + drone_pos0(1) ...
    + drone_speed * cos(alpha) * (t_deploy3+t_explode_delay3);
constraints33 = @(alpha,t_deploy3,drone_speed,t_explode_delay3)  abs(missile3_vel(1)) * (t_deploy3+t_explode_delay3) - missile3_pos0(1) + drone_pos0(1) ...
    + drone_speed * cos(alpha) * (t_deploy3+t_explode_delay3);


% 无人机3，5
drone_dir = [-sin(alpha),cos(alpha)];  % [-pi/2,pi/2]

% 第1个烟雾弹
constraints11 = @(alpha,t_deploy1,drone_speed,t_explode_delay1)  abs(missile1_vel(1)) * (t_deploy1+t_explode_delay1) - missile1_pos0(1) + drone_pos0(1) ...
    +drone_speed * sin(alpha) * (t_deploy1+t_explode_delay1);
constraints12 = @(alpha,t_deploy1,drone_speed,t_explode_delay1)  abs(missile2_vel(1)) * (t_deploy1+t_explode_delay1) - missile2_pos0(1) + drone_pos0(1) ...
    + drone_speed * sin(alpha) * (t_deploy1+t_explode_delay1);
constraints13 = @(alpha,t_deploy1,drone_speed,t_explode_delay1)  abs(missile3_vel(1)) * (t_deploy1+t_explode_delay1) - missile2_pos0(1) + drone_pos0(1) ...
    + drone_speed * sin(alpha) * (t_deploy1+t_explode_delay1);


% 第2个烟雾弹
constraints21 = @(alpha,t_deploy2,drone_speed,t_explode_delay2)  abs(missile1_vel(1)) * (t_deploy2+t_explode_delay2) - missile1_pos0(1) + drone_pos0(1)...
    + drone_speed * sin(alpha) * (t_deploy2+t_explode_delay2);
constraints22 = @(alpha,t_deploy2,drone_speed,t_explode_delay2)  abs(missile2_vel(1)) * (t_deploy2+t_explode_delay2) - missile2_pos0(1) + drone_pos0(1) ...
    + drone_speed * sin(alpha) * (t_deploy2+t_explode_delay2);
constraints23 = @(alpha,t_deploy2,drone_speed,t_explode_delay2)  abs(missile3_vel(1)) * (t_deploy2+t_explode_delay2) - missile3_pos0(1) + drone_pos0(1) ...
    + drone_speed * sin(alpha) * (t_deploy2+t_explode_delay2);

% 第3个烟雾弹
constraints31 = @(alpha,t_deploy3,drone_speed,t_explode_delay3)  abs(missile1_vel(1)) * (t_deploy3+t_explode_delay3) - missile1_pos0(1) + drone_pos0(1) ...
    + drone_speed * sin(alpha) * (t_deploy3+t_explode_delay3);
constraints32 = @(alpha,t_deploy3,drone_speed,t_explode_delay3)  abs(missile2_vel(1)) * (t_deploy3+t_explode_delay3) - missile2_pos0(1) + drone_pos0(1) ...
    + drone_speed * sin(alpha) * (t_deploy3+t_explode_delay3);
constraints33 = @(alpha,t_deploy3,drone_speed,t_explode_delay3)  abs(missile3_vel(1)) * (t_deploy3+t_explode_delay3) - missile3_pos0(1) + drone_pos0(1) ...
    + drone_speed * sin(alpha) * (t_deploy3+t_explode_delay3);


